apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    app: {{.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      name: {{.Name}}
      labels:
        app: {{.Name}}
    spec:
      volumes:
        - name: {{.Name}}-storage
          persistentVolumeClaim:
            claimName: {{.Name}}-pvc
        - name: {{.Name}}-index
          configMap:
            name: {{.Name}}-index-configmap
        - name: {{.Name}}-favicon
          configMap:
            name: {{.Name}}-index-configmap
      containers:
        - name: {{.Name}}-engine
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: {{.Name}}-storage
            - mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              name: {{.Name}}-index
            - mountPath: /usr/share/nginx/html/favicon.ico
              subPath: favicon.ico
              name: {{.Name}}-favicon
      initContainers:
        - name: {{.Name}}-init
          image: yauritux/busybox-curl
          imagePullPolicy: IfNotPresent
          command: [ "sh" ]
          args:
            - -c
            - >-
                wget -nc -P "/mnt/game" --no-check-certificate {{.BundleUrl}} https://js-dos.com/v7/build/releases/latest/js-dos/js-dos.css https://js-dos.com/v7/build/releases/latest/js-dos/js-dos.js https://js-dos.com/v7/build/releases/latest/js-dos/wdosbox.js https://js-dos.com/v7/build/releases/latest/js-dos/wdosbox.wasm https://raw.githubusercontent.com/js-dos/emulators-ui/55c30ae55ebcff2d0bcbe1d8061fd1bdc20d95f0/src/emulators-ui-loader.png;
          volumeMounts:
            - mountPath: /mnt/game
              name: {{.Name}}-storage
      restartPolicy: Always
      