apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-dosbox-assets-pvc
  namespace: {{.Namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Storage}}Mi